name: Continuous Integration
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Install Python 3
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: git clone https://github.com/Joshua-Enrico/sql_enviroment.git

    - name: Install dependencies
      run: pip install sqlalchemy
    - name: Activate enviroment
      run: source sql_enviroment/bin/activate
    - name: Install pep8
      run: pip install pep8
    - name: Run Test
      run: python -m unittest discover tests